include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    unused_element: info
    unused_field: info
    unused_local_variable: info
    unnecessary_null_comparison: info
    unnecessary_non_null_assertion: info
    dead_code: info
  exclude:
    - lib/generated/**
    - ios/**/*.plist
    - macos/**/*.plist

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_unused_constructor_parameters
    - avoid_init_to_null
    - avoid_empty_else
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - prefer_single_quotes
