name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

        **Note: Please write in English only.**

  - type: textarea
    id: problem
    attributes:
      label: Related problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: "e.g., I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Desired solution
      description: What solution would you like to see?
      placeholder: "Describe how you'd like the feature to work..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What alternative solutions have you considered?
      placeholder: "Describe any alternative solutions or features you've considered..."

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
