name: pienews
base: core22
version: "1.0.0"
summary: A modern RSS reader built with Flutter
description: |
  PieNews is a modern RSS reader client that supports multiple RSS services
  including The Old Reader and Feedbin. It features a clean and intuitive
  interface, offline reading support, and article synchronization.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: amd64

apps:
  pienews:
    command: bin/pienews
    extensions: [gnome]
    plugs:
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media
      - gsettings
    slots:
      - dbus-pienews
    common-id: com.github.jasen.pienews

slots:
  dbus-pienews:
    interface: dbus
    bus: session
    name: com.github.jasen.pienews

parts:
  pienews:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libgtk-3-dev
      - libnotify-dev
      - libayatana-appindicator3-dev
    stage-packages:
      - libgtk-3-0
      - libnotify4
      - libayatana-appindicator3-1

  launcher:
    plugin: dump
    source: packaging/snapcraft/
    organize:
      pienews.desktop: usr/share/applications/pienews.desktop
      pienews.png: usr/share/icons/hicolor/512x512/apps/pienews.png
