name: Build Android Dependencies

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: stable

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Build APKs for different architectures
      - name: Build APK (arm64-v8a)
        run: flutter build apk --release --split-per-abi

      - name: Build universal APK
        run: flutter build apk --release

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Rename artifacts
        run: |
          VERSION=${{ inputs.version }}
          mkdir -p build/outputs
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/outputs/PieNews-${VERSION}-Android-arm64.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/outputs/PieNews-${VERSION}-Android-arm7.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/outputs/PieNews-${VERSION}-Android-x86_64.apk
          mv build/app/outputs/flutter-apk/app-release.apk build/outputs/PieNews-${VERSION}-Android-universal.apk
          mv build/app/outputs/bundle/release/app-release.aab build/outputs/PieNews-${VERSION}-Android.aab

      - name: Generate checksums
        run: |
          cd build/outputs
          sha256sum PieNews-*.apk PieNews-*.aab > checksums.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-android
          path: |
            build/outputs/PieNews-*.apk
            build/outputs/PieNews-*.aab
            build/outputs/checksums.txt
